[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0" # Ruff version.
hooks = [
  # Run the linter.
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },

  # Run the formatter.
  { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "https://github.com/facebook/pyrefly-pre-commit"
rev = "0.61.0" # Pyrefly pre-commit hook version.
hooks = [
  {
    id = "pyrefly-check",
    pass_filenames = false,
    additional_dependencies = [
      "ipython",
      "jupyterlab",
      "pytest>=9",
      "pyyaml>=6",
      "stdlib-list>=0.12",
      "tqdm>=4",
      "tree-sitter>=0.20",
      "tree-sitter-language-pack>=0.13",
    ] },
]
